name: Continuous Integration

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

defaults:
    run:
        shell: bash

permissions:
  contents: write

jobs:
    deploy_cv:
        name: deploy_cv
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
            - name: Install Google Fonts
              run: |
                wget -O Poppins.zip https://fonts.google.com/download?family=Poppins
                unzip -d Poppins/ Poppins.zip
                mv Poppins /usr/share/fonts/
                fc-cache -fv
            - name: Typst
              uses: lvignoli/typst-action@main
              with:
                source_file: |
                  typst/cv.typ
            - run: mkdir cv && mv typst/cv.pdf cv/cv.pdf
            - name: deploy
              uses: JamesIves/github-pages-deploy-action@v4
              if: github.ref == 'refs/heads/main'
              with:
                  branch: gh-pages
                  folder: 'cv'
                  clean: true
