name: Continuous Integration

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

defaults:
    run:
        shell: bash

permissions:
  contents: write

jobs:
    deploy_cv:
        name: deploy_cv
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Google Fonts
              run: |
                mkdir -p /usr/share/fonts
                mv fonts /usr/share/fonts/
                fc-cache -fv
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
            - name: Install and run typst
              run: |
                cargo install --locked typst-cli
                typst compile typst/cv.pdf
            - run: mkdir cv && mv cv.pdf cv/cv.pdf
            - name: deploy
              uses: JamesIves/github-pages-deploy-action@v4
              if: github.ref == 'refs/heads/main'
              with:
                  branch: gh-pages
                  folder: 'cv'
                  clean: true
